$schema: https://railway.app/railway.schema.json
version: 2

deploy:
  startCommand: java -Dspring.profiles.active=prod -jar build/libs/*.jar
  healthcheckPath: /actuator/health
  healthcheckTimeout: 300
  restartPolicyType: always

environments:
  production:
    variables:
      SPRING_PROFILES_ACTIVE: prod
      GOOGLE_CLIENT_ID: YOUR_GOOGLE_CLIENT_ID_HERE
      GOOGLE_CLIENT_SECRET: YOUR_GOOGLE_CLIENT_SECRET_HERE
      JWT_SECRET: smartflowerpot_production_secret_2025
      PORT: 8080
